"Small" refactoring to improve kpi collection for consumption path
zalando/nakadi pull request #1338
Opened 2021-11-02 16:07 UTC by antban

1. Now data is published only for streamed batches. In case within kpi collection interval there were no batches streamed for particular event type - the data is not published to internal event type.
2. Reduce code duplication (initialization of kpi event type and parameters)
3. Improve readability

2021-11-02 16:08 UTC, antban commented
:+1: 1:

2021-11-02 16:26 UTC, a1exsh requested changes
Spotted some small issues.

2021-11-02 16:26 UTC, a1exsh commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollector.java
> +    private final long kpiFlushInterval;
```suggestion
    private final long kpiFlushIntervalMs;
```

2021-11-02 16:26 UTC, a1exsh commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollector.java
> +        if ((System.currentTimeMillis() - lastKpiEventSent) > kpiFlushInterval) {
```suggestion
        if ((System.currentTimeMillis() - lastKpiEventSent) > kpiFlushIntervalMs) {
```

2021-11-02 16:26 UTC, a1exsh commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollector.java
> +        kpiData.incBatchesCount();
Yeah, this could be a single method that takes two parameters and increments batch count in one go.

2021-11-02 16:26 UTC, a1exsh commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollectorFactory.java
> +        return new ConsumptionKpiCollector(client, kpiPublisher, kpiDataStreamedEventType, kpiCollectionIntervalMs) {
```suggestion
    public ConsumptionKpiCollector createForLoLA(final Client client) {

        return new ConsumptionKpiCollector(client, kpiPublisher, kpiDataStreamedEventType, kpiCollectionIntervalMs) {
```

2021-11-03 13:07 UTC, antban commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollector.java
> +                .put("batches_streamed", data.getBatchesCount()));
Agree, once we deploy it, will update the schema

2021-11-03 13:10 UTC, antban commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollector.java
> +    private final Map<String, StreamKpiData> kpiDataPerEventType = new HashMap<>();
yes, but I do not feel that we need to change anything

2021-11-03 13:12 UTC, a1exsh commented
:+1:

2022-01-04 13:16 UTC, adyach commented
👍

2022-01-04 13:21 UTC, merged

2022-01-05 10:07 UTC, a1exsh commented on api-consumption/src/main/java/org/zalando/nakadi/service/ConsumptionKpiCollector.java
> +                .put("batches_streamed", data.getBatchesCount()));
Turns out that the schema is validated for internal events as well, but errors are not logged.  It worked only after updating the schema.